// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BotSession struct {
	UserID        int64       `json:"user_id"`
	RoomID        pgtype.UUID `json:"room_id"`
	Notifications bool        `json:"notifications"`
}

type CampaignSummary struct {
	RoomID    pgtype.UUID        `json:"room_id"`
	Summary   string             `json:"summary"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Character struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	UserID    int64              `json:"user_id"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CommandReceipt struct {
	RoomID      pgtype.UUID        `json:"room_id"`
	UserID      int64              `json:"user_id"`
	CommandID   pgtype.UUID        `json:"command_id"`
	RequestHash string             `json:"request_hash"`
	Events      []byte             `json:"events"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type GameEvent struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	ActorID   pgtype.Int8        `json:"actor_id"`
	Type      string             `json:"type"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Sequence  int64              `json:"sequence"`
}

type InventoryItem struct {
	ID          pgtype.UUID `json:"id"`
	CharacterID pgtype.UUID `json:"character_id"`
	Data        []byte      `json:"data"`
}

type Npc struct {
	ID     pgtype.UUID `json:"id"`
	RoomID pgtype.UUID `json:"room_id"`
	Data   []byte      `json:"data"`
}

type Quest struct {
	ID     pgtype.UUID `json:"id"`
	RoomID pgtype.UUID `json:"room_id"`
	Data   []byte      `json:"data"`
}

type Room struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	OwnerID   int64              `json:"owner_id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	State     []byte             `json:"state"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RoomMember struct {
	RoomID   pgtype.UUID        `json:"room_id"`
	UserID   int64              `json:"user_id"`
	Role     string             `json:"role"`
	Ready    bool               `json:"ready"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type Scene struct {
	ID     pgtype.UUID `json:"id"`
	RoomID pgtype.UUID `json:"room_id"`
	Data   []byte      `json:"data"`
}

type TelegramOutbox struct {
	ID          int64              `json:"id"`
	RoomID      pgtype.UUID        `json:"room_id"`
	UserID      int64              `json:"user_id"`
	Body        string             `json:"body"`
	Attempts    int32              `json:"attempts"`
	NextAttempt pgtype.Timestamptz `json:"next_attempt"`
}

type User struct {
	ID        int64              `json:"id"`
	FirstName string             `json:"first_name"`
	Username  string             `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
