// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addEvent = `-- name: AddEvent :exec
INSERT INTO game_events(id,room_id,actor_id,type,payload) VALUES($1,$2,$3,$4,$5)
`

type AddEventParams struct {
	ID      pgtype.UUID `json:"id"`
	RoomID  pgtype.UUID `json:"room_id"`
	ActorID pgtype.Int8 `json:"actor_id"`
	Type    string      `json:"type"`
	Payload []byte      `json:"payload"`
}

func (q *Queries) AddEvent(ctx context.Context, arg AddEventParams) error {
	_, err := q.db.Exec(ctx, addEvent,
		arg.ID,
		arg.RoomID,
		arg.ActorID,
		arg.Type,
		arg.Payload,
	)
	return err
}

const addMember = `-- name: AddMember :exec
INSERT INTO room_members(room_id,user_id,role) VALUES($1,$2,$3) ON CONFLICT DO NOTHING
`

type AddMemberParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID int64       `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) error {
	_, err := q.db.Exec(ctx, addMember, arg.RoomID, arg.UserID, arg.Role)
	return err
}

const clearInventory = `-- name: ClearInventory :exec
DELETE FROM inventory_items WHERE character_id=$1
`

func (q *Queries) ClearInventory(ctx context.Context, characterID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearInventory, characterID)
	return err
}

const createRoom = `-- name: CreateRoom :exec
INSERT INTO rooms(id,code,owner_id,name,state) VALUES($1,$2,$3,$4,$5)
`

type CreateRoomParams struct {
	ID      pgtype.UUID `json:"id"`
	Code    string      `json:"code"`
	OwnerID int64       `json:"owner_id"`
	Name    string      `json:"name"`
	State   []byte      `json:"state"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.Exec(ctx, createRoom,
		arg.ID,
		arg.Code,
		arg.OwnerID,
		arg.Name,
		arg.State,
	)
	return err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters WHERE room_id=$1 AND user_id=$2
`

type DeleteCharacterParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) DeleteCharacter(ctx context.Context, arg DeleteCharacterParams) error {
	_, err := q.db.Exec(ctx, deleteCharacter, arg.RoomID, arg.UserID)
	return err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE id=$1
`

func (q *Queries) DeleteRoom(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoom, id)
	return err
}

const findRoom = `-- name: FindRoom :one
SELECT id, code, owner_id, name, status, state, created_at, updated_at FROM rooms WHERE code=$1
`

func (q *Queries) FindRoom(ctx context.Context, code string) (Room, error) {
	row := q.db.QueryRow(ctx, findRoom, code)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OwnerID,
		&i.Name,
		&i.Status,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotRoom = `-- name: GetBotRoom :one
SELECT room_id FROM bot_sessions WHERE user_id=$1
`

func (q *Queries) GetBotRoom(ctx context.Context, userID int64) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getBotRoom, userID)
	var room_id pgtype.UUID
	err := row.Scan(&room_id)
	return room_id, err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, room_id, user_id, data, created_at FROM characters WHERE id=$1
`

func (q *Queries) GetCharacter(ctx context.Context, id pgtype.UUID) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT id, code, owner_id, name, status, state, created_at, updated_at FROM rooms WHERE id=$1
`

func (q *Queries) GetRoom(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OwnerID,
		&i.Name,
		&i.Status,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, room_id, actor_id, type, payload, created_at, sequence FROM (SELECT id, room_id, actor_id, type, payload, created_at, sequence FROM game_events WHERE room_id=$1 ORDER BY sequence DESC LIMIT 100) recent ORDER BY sequence
`

func (q *Queries) ListEvents(ctx context.Context, roomID pgtype.UUID) ([]GameEvent, error) {
	rows, err := q.db.Query(ctx, listEvents, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameEvent{}
	for rows.Next() {
		var i GameEvent
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.ActorID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.room_id, m.user_id, m.role, m.ready, m.joined_at,u.first_name,u.username FROM room_members m JOIN users u ON u.id=m.user_id WHERE room_id=$1 ORDER BY joined_at
`

type ListMembersRow struct {
	RoomID    pgtype.UUID        `json:"room_id"`
	UserID    int64              `json:"user_id"`
	Role      string             `json:"role"`
	Ready     bool               `json:"ready"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	FirstName string             `json:"first_name"`
	Username  string             `json:"username"`
}

func (q *Queries) ListMembers(ctx context.Context, roomID pgtype.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Role,
			&i.Ready,
			&i.JoinedAt,
			&i.FirstName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT r.id, r.code, r.owner_id, r.name, r.status, r.state, r.created_at, r.updated_at FROM rooms r JOIN room_members m ON m.room_id=r.id WHERE m.user_id=$1 ORDER BY r.created_at DESC
`

func (q *Queries) ListRooms(ctx context.Context, userID int64) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.OwnerID,
			&i.Name,
			&i.Status,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRoom = `-- name: LockRoom :one
SELECT id, code, owner_id, name, status, state, created_at, updated_at FROM rooms WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockRoom(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, lockRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OwnerID,
		&i.Name,
		&i.Status,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockRoomNowait = `-- name: LockRoomNowait :one
SELECT id, code, owner_id, name, status, state, created_at, updated_at FROM rooms WHERE id=$1 FOR UPDATE NOWAIT
`

func (q *Queries) LockRoomNowait(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, lockRoomNowait, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OwnerID,
		&i.Name,
		&i.Status,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM room_members WHERE room_id=$1 AND user_id=$2
`

type RemoveMemberParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.RoomID, arg.UserID)
	return err
}

const saveCharacter = `-- name: SaveCharacter :exec
INSERT INTO characters(id,room_id,user_id,data) VALUES($1,$2,$3,$4) ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data
`

type SaveCharacterParams struct {
	ID     pgtype.UUID `json:"id"`
	RoomID pgtype.UUID `json:"room_id"`
	UserID int64       `json:"user_id"`
	Data   []byte      `json:"data"`
}

func (q *Queries) SaveCharacter(ctx context.Context, arg SaveCharacterParams) error {
	_, err := q.db.Exec(ctx, saveCharacter,
		arg.ID,
		arg.RoomID,
		arg.UserID,
		arg.Data,
	)
	return err
}

const saveItem = `-- name: SaveItem :exec
INSERT INTO inventory_items(id,character_id,data) VALUES($1,$2,$3)
`

type SaveItemParams struct {
	ID          pgtype.UUID `json:"id"`
	CharacterID pgtype.UUID `json:"character_id"`
	Data        []byte      `json:"data"`
}

func (q *Queries) SaveItem(ctx context.Context, arg SaveItemParams) error {
	_, err := q.db.Exec(ctx, saveItem, arg.ID, arg.CharacterID, arg.Data)
	return err
}

const saveNPC = `-- name: SaveNPC :exec
INSERT INTO npcs(id,room_id,data) VALUES($1,$2,$3) ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data
`

type SaveNPCParams struct {
	ID     pgtype.UUID `json:"id"`
	RoomID pgtype.UUID `json:"room_id"`
	Data   []byte      `json:"data"`
}

func (q *Queries) SaveNPC(ctx context.Context, arg SaveNPCParams) error {
	_, err := q.db.Exec(ctx, saveNPC, arg.ID, arg.RoomID, arg.Data)
	return err
}

const saveQuest = `-- name: SaveQuest :exec
INSERT INTO quests(id,room_id,data) VALUES($1,$2,$3) ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data
`

type SaveQuestParams struct {
	ID     pgtype.UUID `json:"id"`
	RoomID pgtype.UUID `json:"room_id"`
	Data   []byte      `json:"data"`
}

func (q *Queries) SaveQuest(ctx context.Context, arg SaveQuestParams) error {
	_, err := q.db.Exec(ctx, saveQuest, arg.ID, arg.RoomID, arg.Data)
	return err
}

const saveRoom = `-- name: SaveRoom :exec
UPDATE rooms SET name=$2,status=$3,state=$4,updated_at=now() WHERE id=$1
`

type SaveRoomParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	Status string      `json:"status"`
	State  []byte      `json:"state"`
}

func (q *Queries) SaveRoom(ctx context.Context, arg SaveRoomParams) error {
	_, err := q.db.Exec(ctx, saveRoom,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.State,
	)
	return err
}

const saveScene = `-- name: SaveScene :exec
INSERT INTO scenes(id,room_id,data) VALUES($1,$2,$3) ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data
`

type SaveSceneParams struct {
	ID     pgtype.UUID `json:"id"`
	RoomID pgtype.UUID `json:"room_id"`
	Data   []byte      `json:"data"`
}

func (q *Queries) SaveScene(ctx context.Context, arg SaveSceneParams) error {
	_, err := q.db.Exec(ctx, saveScene, arg.ID, arg.RoomID, arg.Data)
	return err
}

const saveSummary = `-- name: SaveSummary :exec
INSERT INTO campaign_summaries(room_id,summary) VALUES($1,$2) ON CONFLICT(room_id) DO UPDATE SET summary=EXCLUDED.summary,updated_at=now()
`

type SaveSummaryParams struct {
	RoomID  pgtype.UUID `json:"room_id"`
	Summary string      `json:"summary"`
}

func (q *Queries) SaveSummary(ctx context.Context, arg SaveSummaryParams) error {
	_, err := q.db.Exec(ctx, saveSummary, arg.RoomID, arg.Summary)
	return err
}

const selectBotRoom = `-- name: SelectBotRoom :exec
INSERT INTO bot_sessions(user_id,room_id) VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET room_id=EXCLUDED.room_id
`

type SelectBotRoomParams struct {
	UserID int64       `json:"user_id"`
	RoomID pgtype.UUID `json:"room_id"`
}

func (q *Queries) SelectBotRoom(ctx context.Context, arg SelectBotRoomParams) error {
	_, err := q.db.Exec(ctx, selectBotRoom, arg.UserID, arg.RoomID)
	return err
}

const setReady = `-- name: SetReady :exec
UPDATE room_members SET ready=$3 WHERE room_id=$1 AND user_id=$2
`

type SetReadyParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID int64       `json:"user_id"`
	Ready  bool        `json:"ready"`
}

func (q *Queries) SetReady(ctx context.Context, arg SetReadyParams) error {
	_, err := q.db.Exec(ctx, setReady, arg.RoomID, arg.UserID, arg.Ready)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users(id,first_name,username) VALUES($1,$2,$3) ON CONFLICT(id) DO UPDATE SET first_name=EXCLUDED.first_name,username=EXCLUDED.username
`

type UpsertUserParams struct {
	ID        int64  `json:"id"`
	FirstName string `json:"first_name"`
	Username  string `json:"username"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser, arg.ID, arg.FirstName, arg.Username)
	return err
}
